mapping:
    xi:include:
        - @href: "equilibrium"
        - @href: "magnetics"
        - @href: "pf_active"
        - @href: "tf"
        - @href: "wall"
    data:
        - a: 1
          b: 2
          c: 3
        - "hello"